INSERT INTO book_table (title, author, year_of_publishing) VALUES ('To Kill a Mockingbird', 'Harper Lee', 1960);
INSERT INTO book_table (title, author, year_of_publishing) VALUES ('One Hundred Years of Solitude', 'Gabriel García Márquez', 1967);
INSERT INTO book_table (title, author, year_of_publishing) VALUES ('The Great Gatsby', 'F. Scott Fitzgerald', 1925);
INSERT INTO book_table (title, author, year_of_publishing) VALUES ('War and Peace', 'Leo Tolstoy', 1869);
INSERT INTO book_table (title, author, year_of_publishing) VALUES ('Pride and Prejudice', 'Jane Austen', 1813);
INSERT INTO book_table (title, author, year_of_publishing) VALUES ('The Brothers Karamazov', 'Fyodor Dostoevsky', 1880);
INSERT INTO book_table (title, author, year_of_publishing) VALUES ('The Alchemist', 'Paulo Coelho', 1988);
INSERT INTO book_table (title, author, year_of_publishing) VALUES ('The Book Thief', 'Markus Zusak', 2005);
INSERT INTO book_table (title, author, year_of_publishing) VALUES ('Crime and Punishment', 'Fyodor Dostoevsky', 1866);
INSERT INTO book_table (title, author, year_of_publishing) VALUES ('The Catcher in the Rye', 'J.D. Salinger', 1951);
INSERT INTO book_table (title, author, year_of_publishing) VALUES ('The Kite Runner', 'Khaled Hosseini', 2003);
INSERT INTO book_table (title, author, year_of_publishing) VALUES ('Brave New World', 'Aldous Huxley', 1932);
INSERT INTO book_table (title, author, year_of_publishing) VALUES ('Life of Pi', 'Yann Martel', 2001);
INSERT INTO book_table (title, author, year_of_publishing) VALUES ('The Old Man and the Sea', 'Ernest Hemingway', 1952);
INSERT INTO book_table (title, author, year_of_publishing) VALUES ('The Little Prince', 'Antoine de Saint-Exupéry', 1943);
INSERT INTO book_table (title, author, year_of_publishing) VALUES ('Midnight''s Children', 'Salman Rushdie', 1981);
INSERT INTO book_table (title, author, year_of_publishing) VALUES ('Don Quixote', 'Miguel de Cervantes', 1605);
INSERT INTO book_table (title, author, year_of_publishing) VALUES ('A Tale of Two Cities', 'Charles Dickens', 1859);
INSERT INTO book_table (title, author, year_of_publishing) VALUES ('Things Fall Apart', 'Chinua Achebe', 1958);
